export const createUserData = (email: string, password: string) => ({
  name: "Api Test User",
  email,
  password,
  title: "Mrs",
  birth_date: "31",
  birth_month: "01",
  birth_year: "1997",
  firstname: "Api",
  lastname: "Tester",
  company: "Test Company",
  address1: "Test Street 1",
  address2: "Flat 2",
  country: "Canada",
  zipcode: "12345",
  state: "California",
  city: "Toronto",
  mobile_number: "1234567890",
});

export const updatedUserData = (email: string, password: string) => ({
  name: "Api Test User2",
  email,
  password,
  title: "Miss",
  birth_date: "31",
  birth_month: "01",
  birth_year: "1997",
  firstname: "Api",
  lastname: "Tester",
  company: "Test Company 2",
  address1: "Test Street 1",
  address2: "Flat 2",
  country: "Canada",
  zipcode: "54321",
  state: "California",
  city: "Toronto",
  mobile_number: "1234567890",
});